[WTEL-2801] feature: Add agent's chat username
webitel/chat_manager pull request #23
Opened 2024-12-03 13:24 UTC by nazarwebitel

# Pull Request

## Jira

[WTEL-2801](https://webitel.atlassian.net/browse/WTEL-2801) - Agent's nickname

## Type of Change
- [x] Feature
- [ ] Bugfix
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

2024-12-05 14:11 UTC, ashalaenko commented on internal/repo/sqlx/user.go
> +	query := `
Не знаю як у нас принято : можливі краще буде вибрати щ бази три поля , name, dsiplay_name, username, і вже в коді перевіряти 
Плюси :
 - простіший запит до бази
 - логіка формування на рівні коду 
 
Мінусі : додатковий код

2024-12-05 14:13 UTC, ashalaenko commented on cmd/chat/service.go
> +		Name:           user.DisplayName,
можливо краще також додати окреме поле DisplayName в структуру і використовувати саме його, так як Name ще може знадобитись,  тим паче що в структурі воно має теги і для бази і джейсону
```
Name        string         `db:"name" json:"name"`
```

чи це повпливає на фронт ?

2024-12-05 14:15 UTC, ashalaenko commented on internal/util/parse.go
> +package util
з появою цього пакету в майбутньому можливо буде винести функції накшталт remove і contains ))

2024-12-05 21:47 UTC, nazarwebitel commented on internal/util/parse.go
> +func ParseFullName(fullName string) (firstName, lastName string) {
хороша ідея, треба потроху збільшувати ковередж тестами у цьому сервісі)

2024-12-05 21:51 UTC, nazarwebitel commented on internal/util/parse.go
> +package util
хаххаха це точно))

2024-12-05 21:59 UTC, nazarwebitel commented on internal/repo/sqlx/user.go
> +	query := `
чесно не знаю як нас прийнято) загалом COALESCE та NULLIF це швидкі операції для СУБД тим більше ми тут витягаємо 1 рядок з БД, тому може поки залишимо як є?

2024-12-05 22:27 UTC, nazarwebitel commented on cmd/chat/service.go
> +		Name:           user.DisplayName,
Загальна ідея DisplayName в тому  щоб адмін міг задати ім'я яке буде показуватись клієнту під час підключення до чату (можливо ще десь у майбутньому).

Я погоджуюсь що краще було б 2-ва поля але тоді питання дублювання даних чи ок, тому що channel зберігає у собі userID і параметри юзера додатково, тепер їх буде 2: Name, DisplayName. Чи це ОК?

2024-12-05 22:28 UTC, nazarwebitel commented on cmd/chat/service.go
> +		Name:           user.DisplayName,
Доречі я тут подумав може його назвати краще ExternalDisplayName або просто ExternalName. Може так зрозуміліше для чого це поле?

2024-12-06 13:34 UTC, nazarwebitel commented on internal/repo/sqlx/models.go
> +	PublicName  sql.NullString `db:"public_name" json:"public_name"`
Назвав його PublicName тому що і так зрозуміло що це відноситься до чату (канали тільки з чатами). А приставна Public також помагає зрозуміти різницю між Name (по суті приватним і'мям) і публічним.

2024-12-09 13:59 UTC, ashalaenko requested changes

2024-12-09 13:59 UTC, ashalaenko commented on internal/event_router/event_router.go
> +				fullName := channel.Name
можливо цей код винесоти в функцію на структуру Channel в моделі ? типу щоб було 
```
firstName , lastName := channel.GetFirstLastName()
```

or
  
```
firstName, lastName := util.ParseFullName(channel.GetFullName())
```

останнє навіть краще, напевне

2024-12-09 13:59 UTC, ashalaenko commented on internal/repo/sqlx/models.go
> +	ChatPublicName sql.NullString `db:"chat_public_name" json:"chat_public_name"`
тут не до кінця зрозуміло  : а може бути ще ChatPrivateName?
наскільки я зрозумів логіку Сергія , ідея була в тому щоб додати поля для можливих каналів зв"язку, щоось накшталт
``` Name
ChatName
CallName
``` 
і тд.

не розумію навіщо тут паблік ?

2024-12-09 13:59 UTC, ashalaenko commented on internal/repo/sqlx/models.go
> +	ChatPublicName sql.NullString `db:"chat_public_name" json:"chat_public_name"`
і ось тут ми приходимо о того, що я писав вище : 
 - у нас поле в базі заявлене як nullable , тому мы маємо працювати з поінтерами і тд
 - но на справді, там де ми його вибириємо воно не буде нулем ніколи, так як ми його вибираємо через 
 ```
COALESCE(NULLIF(u.chat_public_name, ''), NULLIF(u.name, ''), u.username) AS chat_public_name
```
 
що приводить до того, що у нас логіка роботи з даними розмивається.
Зараз напевно нічого змінювати не потрібно, проте в майбутньому можливо.

2024-12-09 13:59 UTC, ashalaenko commented on internal/repo/sqlx/repository.go
> +	GetWebitelUserByID(ctx context.Context, userID, domainID int64) (*WebitelUser, error)
а чому ти тут змінив id  на userID?

2024-12-09 14:05 UTC, nazarwebitel commented on internal/repo/sqlx/repository.go
> +	GetWebitelUserByID(ctx context.Context, userID, domainID int64) (*WebitelUser, error)
добавився ще 1 параметр id (domainID) тому і змінив на userID щоб було зрозуміліше

2024-12-11 09:58 UTC, ashalaenko approved these changes

2024-12-11 09:59 UTC, merged