[WTEL-5618] bugfix: Two buttons appear below the text in the menu component
webitel/chat_manager pull request #24
Opened 2024-12-04 10:06 UTC by nazarwebitel

# Pull Request

## Jira

[WTEL-5618](https://webitel.atlassian.net/browse/WTEL-5618) - Two buttons appear below the text in the menu component

## Type of Change
- [ ] Feature
- [x] Bugfix
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

[WTEL-5618]: https://webitel.atlassian.net/browse/WTEL-5618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-05 15:03 UTC, ashalaenko commented on bot/api.go
> +					"broadcast: type is 'text' file is not accepted",
probably something like this
type 'text' does not accept files

2024-12-05 21:04 UTC, nazarwebitel commented on bot/telegram/http/telegram.go
> +		err := sendMessageBuilder.SetMergedKeyboad(buttons)
так, це помилка

2024-12-05 21:04 UTC, nazarwebitel commented on bot/telegram/internal/builder/send_message.go
> +	var keyboad [][]telegram.KeyboardButton
так, це помилка

2024-12-05 21:11 UTC, nazarwebitel commented on bot/telegram/internal/builder/send_message.go
>  	return nil
загалом коли це писав хотів зробити уніфікований виклик функцій білдера, щоб кожен метод міг повернути помилку вразі чого, а тут немає потреби повертати помилку тому nil. але якщо що можу переписати і прибрати повернення помилки

2024-12-05 21:17 UTC, nazarwebitel commented on bot/telegram/internal/builder/send_message.go
> +				return b.SetRemoveKeyboard()
це ще з минулих реалізацій, там по логіці було таке якщо якщо ми зустрічаємо наприклад кнопку з типом "clear" тоді ми повертаємо пусту клавіатуру і немає сенсу ітеруватись циклом і будувати її далі

2024-12-05 21:25 UTC, nazarwebitel commented on bot/telegram/internal/builder/send_message.go
> +	ignoreTypes := []string{"email", "mail"}
думаю так, константами буде краще

2024-12-12 11:02 UTC, ashalaenko requested changes

2024-12-12 11:02 UTC, ashalaenko commented on bot/viber/viber.go
> +		for _, fail := range res.FailStatus {
Потрібно дізнатися як хендлити і чии потрібно хендлити взагалі ситуації накшталт : 
 - файл відправився, а підпис до нього ні
 - файл НЕ відправився, а підпис до нього так

2024-12-12 11:02 UTC, ashalaenko commented on bot/viber/sender.go
> +		messageWithCaption.PeerId = peerIDs
тут ми просто сетапимо поля, а вище - через сетери

2024-12-12 15:23 UTC, ashalaenko approved these changes

2024-12-12 16:21 UTC, merged